version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-1067
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ticketing1_1067-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-1067
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-1067
    container_name: authproxy-1067
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-1067
    container_name: securitymanager-1067
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-1067
    container_name: camundasvc-1067
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-1067
    container_name: apigateway-1067
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - types1
      - severity1
      - tickets1



  types1: 
    build: ../../../application/services/custom_services/types1
    image: types1-1067
    container_name: types1-1067
    ports: 
      - 8007:8007
    env_file: .env
    depends_on:
      - mongo

  severity1: 
    build: ../../../application/services/custom_services/severity1
    image: severity1-1067
    container_name: severity1-1067
    ports: 
      - 8008:8008
    env_file: .env
    depends_on:
      - mongo

  tickets1: 
    build: ../../../application/services/custom_services/tickets1
    image: tickets1-1067
    container_name: tickets1-1067
    ports: 
      - 8009:8009
    env_file: .env
    depends_on:
      - mongo


volumes:
  ticketing1_1067-volume:
    driver: local
